allow exemptions for requiredprobes policy
open-policy-agent/gatekeeper-library pull request #303
Opened 2023-03-13 22:50 UTC by zahodi

This policy allows for definition of a list of containers that should be excluded from the requiredprobes policy.

2023-04-17 16:51 UTC, zahodi commented
@ritazh I need some help on this, when I run `make generate generate-website-docs generate-artifacthub-artifacts` my code gets removed. Am I following something not in order?

2023-04-27 21:24 UTC, JaydipGabani commented
@zahodi `make generate generate-website-docs generate-artifacthub-artifacts` generates files based on `src/general` dir, and since you are not updating root template for `requiredprobes` the command you are running overwrites your changes. You need to update [constraint.tmpl](https://github.com/open-policy-agent/gatekeeper-library/blob/master/src/general/requiredprobes/constraint.tmpl) with the changes you want to make. For rego changes, you might need to update [src.rego](https://github.com/open-policy-agent/gatekeeper-library/blob/master/src/general/requiredprobes/src.rego) and for `lib` you are trying to add here is an [examlpe template](https://github.com/open-policy-agent/gatekeeper-library/blob/master/src/general/containerlimits/constraint.tmpl#L43), you can follow similar pattern. 

Once you are done manking changes in `src/general/requiredprobes`, in your local delete the `artifacthub/library/general/requiredprobs/1.0.1` dir and generate it again using the aformentioned command

2023-04-27 21:28 UTC, JaydipGabani requested changes

2023-04-27 21:28 UTC, JaydipGabani commented on library/general/requiredprobes/template.yaml
> +        import data.lib.exempt_container.is_exempt
Update `src/general/requiredprobes/src.rego` with the rego changes you are trying to make

2023-04-27 21:28 UTC, JaydipGabani commented on library/general/requiredprobes/template.yaml
> +      libs:
add this in `src/general/requiredprobes/constraint.tmpl`

2023-09-13 18:18 UTC, closed without merging