fix: fixing faluty examples
open-policy-agent/gatekeeper-library pull request #485
Opened 2024-02-16 17:17 UTC by JaydipGabani

**What this PR does / why we need it**: fixes #484 

**Which issue(s) does this PR fix** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

2024-02-16 17:48 UTC, apeabody commented
Hi @JaydipGabani - Can you please take a look at my comment here: https://github.com/open-policy-agent/gatekeeper-library/issues/484#issuecomment-1948976882 Thanks!

2024-02-16 20:39 UTC, apeabody requested changes

2024-02-16 20:39 UTC, apeabody commented on website/docs/validation/uniqueserviceselector.md
> +Usagea
```suggestion
Usage
```

2024-02-21 02:40 UTC, maxsmythe approved these changes
LGTM

2024-02-21 16:12 UTC, apeabody submitted a review, later dismissed
Thanks @JaydipGabani! - Per our conversation I would suggest calling this PR to something like "fix: coordinate example resources", or at the very least correct "faulty".

2024-02-22 17:13 UTC, JaydipGabani commented
@apeabody this is turning out to be somewhat complex. CI is falling for `ingress-host` because in bats tests `example_allowed` are getting deleted right after the test for them is successful. So by the time when `example_disallowed` are created there is no `example_allowed` resource in the cluster to fail against (this case is being handled with `example_inventory` which we are deleting). If I modify the tests to delete `example_allowed` after the tests are conducted for `example_disallwed`, then other tests fail. Might be worth figuring out how to bring inventory to website directly rather than figuring this out and then eventually bring inventory to website.

wdyt?

2024-02-22 18:59 UTC, JaydipGabani commented
Closing this PR in favor of bringing inventory to website.
@maxsmythe @apeabody

2024-02-22 18:59 UTC, closed without merging