chore: adding CEL for psp-host-filesystem
open-policy-agent/gatekeeper-library pull request #547
Opened 2024-06-05 21:36 UTC by JaydipGabani

**What this PR does / why we need it**:

**Which issue(s) does this PR fix** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #541 

**Special notes for your reviewer**:

2024-07-03 22:32 UTC, maxsmythe requested changes

2024-07-03 22:32 UTC, maxsmythe commented on artifacthub/library/pod-security-policy/host-filesystem/1.1.0/samples/psp-host-filesystem/example_allowed.yaml
> +    app: nginx-host-filesystem-disallowed
Do we need the app label? The allowed/disallowed is out of sync for a number of files.

2024-07-03 22:32 UTC, maxsmythe commented on library/pod-security-policy/host-filesystem/template.yaml
> +              has(variables.params) ? (has(variables.params.allowedHostPaths) ? variables.params.allowedHostPaths : []) : []
nit: If you use !has() the chaining should look a bit cleaner and will end with the user-input variable value

2024-07-03 22:32 UTC, maxsmythe commented on library/pod-security-policy/host-filesystem/template.yaml
> +                    !(allowedHostPath.readOnly == true) ||
nit: no need for `== true` in `allowedHostPath.readOnly == true` (already a bool), also we should allow for the possibility that the parameter will not be set (i.e. has() == false)

2024-07-03 22:32 UTC, maxsmythe commented on library/pod-security-policy/host-filesystem/template.yaml
> +                      c.volumeMounts.exists(m, m.name == volume.name && !m.readOnly))))))
we should account for if readOnly is missing (has() == false) (both for the constraint parameter and for the VolumeMount object)

2024-09-03 23:03 UTC, sozercan approved these changes
LGTM

2024-09-04 01:23 UTC, maxsmythe approved these changes
LGTM

2024-09-04 01:52 UTC, merged