fix(k8spspreadonlyrootfilesystem): CEL support wildcard in exemptImages
open-policy-agent/gatekeeper-library pull request #584
Opened 2024-08-26 22:44 UTC by julianKatz

Despite it being non-sensical to put a `*` in exemptImages (functionally disabling the policy), this is supported in the existing rego implementation of the template.

Thus, not doing it in the CEL implementation is an inconsistency and a breaking change.

This PR upholds the contract by adding support for `*` as an exemptImage.

2024-08-27 00:34 UTC, maxsmythe commented
I think "*" should work with the code as-is. "*" gets translated as "ignore any image that uses the empty string as a prefix", which is effectively any image string.

Has the pre-existing code been tested to see if it already behaves correctly?

2024-08-27 19:55 UTC, maxsmythe approved these changes
LGTM, thanks for the fix!

2024-08-29 19:42 UTC, JaydipGabani commented on library/pod-security-policy/read-only-root-filesystem/samples/wildcard_support/full_wildcard_constraint.yaml
rename this to `constraint.yaml`, to fix CI.

2024-08-29 19:43 UTC, JaydipGabani commented on artifacthub/library/pod-security-policy/read-only-root-filesystem/1.1.1/samples/wildcard-support/constraint.yaml
is this file added by mistake? I do not see it being used anywhere.

2024-08-29 19:56 UTC, JaydipGabani requested changes

2024-08-29 19:56 UTC, JaydipGabani commented on artifacthub/library/pod-security-policy/read-only-root-filesystem/1.1.1/samples/wildcard_support/example_safe_image_prefix.yaml
We should follow `example_allowed_`/`example_disallowed_` naming standard for consistancy and for bats test.

2024-08-29 19:56 UTC, JaydipGabani commented on library/pod-security-policy/read-only-root-filesystem/samples/wildcard_support/prefix_matching_constraint.yaml
Make sure that each `constraint.yaml` with `allowed/disallowed` exmaples are grouped together in subdirs (one `constraint` per subdir). This is needed to effectively generate website, otherwise the order and information on the generated README gets scrambled and confusing.

2024-08-29 20:26 UTC, julianKatz commented on library/pod-security-policy/read-only-root-filesystem/samples/wildcard_support/full_wildcard_constraint.yaml
Made individual folders for each constraint and renamed constraint files to `constraint.yaml`

2024-08-29 20:29 UTC, julianKatz commented on artifacthub/library/pod-security-policy/read-only-root-filesystem/1.1.1/samples/wildcard_support/example_safe_image_prefix.yaml
Done.  All my new objects are either `constraint.yaml` or allowed/disallowed objects matching `example_allowed.*.yaml` or `example_disallowed.*.yaml`

2024-08-29 20:29 UTC, julianKatz commented on artifacthub/library/pod-security-policy/read-only-root-filesystem/1.1.1/samples/wildcard-support/constraint.yaml
I regenerated the entire `artifacthub/.../read-only-root-filesystem/1.1.1` and this is now removed.

2024-08-29 20:41 UTC, apeabody approved these changes
LGTM

2024-08-29 20:44 UTC, JaydipGabani commented on library/pod-security-policy/read-only-root-filesystem/samples/wildcard_support/prefix_matching_constraint.yaml
Yip thats sufficient.

2024-08-29 20:45 UTC, JaydipGabani approved these changes
LGTM

2024-08-29 21:21 UTC, merged