fix(k8spspprocmount): fix exemptImages support
open-policy-agent/gatekeeper-library pull request #588
Opened 2024-08-28 22:00 UTC by julianKatz

I recently found (#584) that some K8sNativeValidation implementations of certain templates that iterate over and exempt containers by image had a bug preventing the exemption logic from working.

I've fixed that bug here by mapping from `container` struct to `container.image` string.  I've also added a suite test to verify this. That case fails without the change to the CEL logic.

2024-08-29 20:10 UTC, JaydipGabani requested changes

2024-08-29 20:10 UTC, JaydipGabani commented on artifacthub/library/pod-security-policy/proc-mount/1.1.1/samples/psp-proc-mount/example_disallowed_exempt_image.yaml
This should be renamed to `example_allowed_exempt_image.yaml` as we are not expecting it to generate violation. Renaming the file should also fix the CI.

2024-08-29 21:26 UTC, julianKatz commented on artifacthub/library/pod-security-policy/proc-mount/1.1.1/samples/psp-proc-mount/example_disallowed_exempt_image.yaml
Updated this to be an `example_allowed` as you suggested

2024-08-29 21:26 UTC, julianKatz commented
Thanks for the review @JaydipGabani!  This is ready for another look.

2024-08-29 23:00 UTC, JaydipGabani approved these changes
lgtm

2024-08-29 23:03 UTC, apeabody approved these changes
LGTM

2024-08-30 19:40 UTC, maxsmythe approved these changes
LGTM

2024-08-30 20:10 UTC, merged

2024-08-30 20:45 UTC, Markieta commented
@julianKatz I just pulled this update and it seems to break functionality getting the following violations:

```
failed expression: (has(request.operation) && request.operation == "UPDATE") || size(variables.badContainers) == 0
```