fix(k8spsphostnetworkingports): CEL fixes for hostNetwork variable and message
open-policy-agent/gatekeeper-library pull request #589
Opened 2024-08-29 00:22 UTC by julianKatz

My updates to the suite.yaml file yielded an expected failure due to an incorrect CEL expression:

```
        unexpected number of violations: got 1 violations but want none: got messages [failed expression: (has(request.operation) && request.operation == "UPDATE") ||
(!has(variables.params.hostNetwork) || !variables.params.hostNetwork ? (has(variables.anyObject.spec.hostNetwork) && !variables.anyObject.spec.hostNetwork) : true)]
```

By contrast, a run of `gator verify -v .
--enable-k8s-native-validation=false` yielded a fully passing suite.yaml.

This expression was actually failing due to its `messageExpression`, as non-primitive types cannot be combined with strings as in some interpreted languages (like rego).  Unfortunately the compiler does not indicate that the messageExpression is the source of the problem.

Once the message was fixed, I resolved the incorrect violation expression to fix the bug in the handling of params.hostNetwork.

2024-08-29 18:45 UTC, JaydipGabani requested changes

2024-08-29 18:45 UTC, JaydipGabani commented on library/pod-security-policy/host-network-ports/template.yaml
Update patch version to `1.1.3`

2024-08-29 21:30 UTC, julianKatz commented on library/pod-security-policy/host-network-ports/template.yaml
Bumped the patch version and re-generated.  Ready for another look!

2024-08-30 18:54 UTC, apeabody approved these changes
Thanks @julianKatz!

2024-08-30 19:42 UTC, maxsmythe approved these changes
LGTM

2024-08-30 20:16 UTC, JaydipGabani approved these changes

2024-08-30 20:32 UTC, merged